s3:
    access_key_id: 'ACCESS KEY'
    secret_access_key: 'SERECT KEY'
    bucket_name: 'BUCKET NAME'
    

image_settings:
    horizontal_res: 800
    vertical_res: 400
    file_name: 'test'
    file_extension: '.jpg'
    folder_name: 'images'
    awb_mode: 'auto'
    photo_interval: 10

debug: true
